services:
  auto-ai-router-01:
    image: ghcr.io/mixaill76/auto_ai_router:dev-latest
    restart: unless-stopped

    ports:
      - "8080:8080"

    configs:
      - source: auto-ai-router-01-config
        target: /app/config.yaml

    depends_on:
      ger01:
        condition: service_healthy
      fin01:
        condition: service_healthy

  ger01:
    image: ghcr.io/mixaill76/auto_ai_router:dev-latest
    restart: unless-stopped
    configs:
      - source: ger01-config
        target: /app/config.yaml

    depends_on:
      fra01:
        condition: service_healthy

  fin01:
    image: ghcr.io/mixaill76/auto_ai_router:dev-latest
    restart: unless-stopped
    configs:
      - source: fin01-config
        target: /app/config.yaml

  fra01:
    image: ghcr.io/mixaill76/auto_ai_router:dev-latest
    restart: unless-stopped
    configs:
      - source: fra01-config
        target: /app/config.yaml

configs:
  auto-ai-router-01-config:
    content: |
      server:
        port: 8080
        max_body_size_mb: 100
        request_timeout: 5m
        logging_level: debug  # Options: info, debug, error
        master_key: "sk-your-master-key-here"  # Required: Master key for client authentication

      monitoring:
        prometheus_enabled: true
        log_errors: false

      credentials:
      - name: "ger01"
        type: "proxy"
        api_key: sk-ger01-key
        base_url: http://ger01:8080

      - name: "fin01"
        type: "proxy"
        is_fallback: true
        api_key: sk-fin01-key
        base_url: http://fin01:8080

      - name: "fra01"
        type: "proxy"
        is_fallback: true
        api_key: sk-fra01-key
        base_url: http://fra01:8080

  ger01-config:
    content: |
      server:
        port: 8080
        max_body_size_mb: 100
        request_timeout: 5m
        logging_level: debug  # Options: info, debug, error
        master_key: "sk-ger01-key"  # Required: Master key for client authentication

      monitoring:
        prometheus_enabled: true
        log_errors: false

      credentials:
      - name: "openai_router_2"
        type: "openai"
        api_key: ${OPENAI_API_KEY}
        base_url: ${OPENAI_BASE_URL}

      models:
      - name: gpt-5-mini
        rpm: 1
        credential: openai_router_2

  fin01-config:
    content: |
      server:
        port: 8080
        max_body_size_mb: 100
        request_timeout: 5m
        logging_level: debug  # Options: info, debug, error
        master_key: "sk-fin01-key"  # Required: Master key for client authentication

      monitoring:
        prometheus_enabled: true
        log_errors: false

      credentials:
      - name: "openai_router_3"
        type: "openai"
        api_key: ${OPENAI_API_KEY}
        base_url: ${OPENAI_BASE_URL}

      models:
      - name: gpt-5-mini
        credential: openai_router_3
        rpm: 1

  fra01-config:
    content: |
      server:
        port: 8080
        max_body_size_mb: 100
        request_timeout: 5m
        logging_level: debug  # Options: info, debug, error
        master_key: "sk-fra01-key"  # Required: Master key for client authentication

      monitoring:
        prometheus_enabled: true
        log_errors: false

      credentials:
      - name: "openai_router_4"
        type: "openai"
        api_key: ${OPENAI_API_KEY}
        base_url: ${OPENAI_BASE_URL}

      models:
      - name: gpt-5-mini
        rpm: 1
        credential: openai_router_4
