package proxy

import (
	"net/http"
	"strconv"
	"strings"

	"github.com/mixaill76/auto_ai_router/internal/config"
	dbmodels "github.com/mixaill76/auto_ai_router/internal/litellmdb/models"
	"github.com/mixaill76/auto_ai_router/internal/shadowcontext"
)

const (
	airEventIDHeader                       = "X-Vsellm-Air-Event-Id"
	liteLLMKeySpendHeader                  = "X-Litellm-Key-Spend"
	liteLLMKeyMaxBudgetHeader              = "X-Litellm-Key-Max-Budget"
	liteLLMKeyRPMLimitHeader               = "X-Litellm-Key-Rpm-Limit"
	liteLLMKeyTPMLimitHeader               = "X-Litellm-Key-Tpm-Limit"
	liteLLMResponseCostHeader              = "X-Litellm-Response-Cost"
	liteLLMResponseCostOriginalHeader      = "X-Litellm-Response-Cost-Original"
	liteLLMResponseCostDiscountHeader      = "X-Litellm-Response-Cost-Discount-Amount"
	liteLLMResponseCostMarginAmountHeader  = "X-Litellm-Response-Cost-Margin-Amount"
	liteLLMResponseCostMarginPercentHeader = "X-Litellm-Response-Cost-Margin-Percent"
	accelBufferingHeader                   = "X-Accel-Buffering"
)

// hopByHopHeaders are headers that should not be proxied.
// These are hop-by-hop headers as defined in RFC 7230 Section 6.1.
// They are meant for single HTTP connection and must not be forwarded to the next hop.
var hopByHopHeaders = map[string]bool{
	"Connection":          true,
	"Keep-Alive":          true,
	"Proxy-Authenticate":  true,
	"Proxy-Authorization": true,
	"TE":                  true,
	"Trailer":             true,
	"Transfer-Encoding":   true,
	"Upgrade":             true,
}

// privacyHeaders are headers that reveal client IP or routing information.
// These are added by reverse proxies/load balancers and must not be forwarded
// to upstream AI providers to protect user privacy.
var privacyHeaders = map[string]bool{
	"X-Forwarded-For":     true,
	"X-Forwarded-Host":    true,
	"X-Forwarded-Port":    true,
	"X-Forwarded-Proto":   true,
	"X-Forwarded-Server":  true,
	"X-Real-Ip":           true,
	"X-Original-For":      true,
	"X-Client-Ip":         true,
	"X-Cluster-Client-Ip": true,
	"Forwarded":           true,
	"Via":                 true,
}

// isPrivacyHeader checks if a header reveals client IP or routing information.
func isPrivacyHeader(key string) bool {
	return privacyHeaders[key]
}

// isHopByHopHeader checks if a header should not be proxied.
// Returns true for hop-by-hop headers that must not be forwarded to upstream.
// RFC 7230: https://tools.ietf.org/html/rfc7230#section-6.1
func isHopByHopHeader(key string) bool {
	return hopByHopHeaders[key]
}

// isProxyOwnedResponseHeader identifies response headers whose value is
// generated by AIR and must not be duplicated or overridden by an upstream.
func isProxyOwnedResponseHeader(key string) bool {
	switch http.CanonicalHeaderKey(key) {
	case airEventIDHeader,
		shadowcontext.CallIDHeader,
		liteLLMKeySpendHeader,
		liteLLMKeyMaxBudgetHeader,
		liteLLMKeyRPMLimitHeader,
		liteLLMKeyTPMLimitHeader,
		liteLLMResponseCostHeader,
		liteLLMResponseCostOriginalHeader,
		liteLLMResponseCostDiscountHeader,
		liteLLMResponseCostMarginAmountHeader,
		liteLLMResponseCostMarginPercentHeader,
		accelBufferingHeader:
		return true
	default:
		return false
	}
}

// setSingleHeaderValue removes every casing of name before installing one
// canonical value. net/http canonicalizes wire headers, but requests created by
// in-process callers can still contain differently-cased map keys.
func setSingleHeaderValue(headers http.Header, name, value string) {
	if headers == nil {
		return
	}
	for key := range headers {
		if strings.EqualFold(key, name) {
			delete(headers, key)
		}
	}
	headers.Set(name, value)
}

// initializeAIREventIDHeaders establishes AIR as the sole owner of the
// per-request event ID. The request copy is intentionally forwarded to every
// provider attempt; the response copy lets clients correlate that provider
// traffic with the durable SpendLog event. The ID is local to this AIR hop: a
// downstream AIR replaces it at its own ingress. X-Aar-Proxy-Client is only a
// response-metadata marker, not authentication, and must never authorize reuse
// of an inbound event ID.
func initializeAIREventIDHeaders(w http.ResponseWriter, r *http.Request, eventID string) {
	if r.Header == nil {
		r.Header = make(http.Header)
	}
	setSingleHeaderValue(r.Header, airEventIDHeader, eventID)
	setSingleHeaderValue(w.Header(), airEventIDHeader, eventID)
}

// shouldExposeLiteLLMFinancialHeaders assigns ownership of the public
// X-Litellm financial headers to the outermost gateway. A valid signed shadow
// context proves that this AIR request is nested behind LiteLLM, which will
// publish its own client-facing key limits and cost. Missing or invalid
// contexts retain direct AIR behavior; neither is proof of a trusted chain.
func shouldExposeLiteLLMFinancialHeaders(logCtx *RequestLogContext) bool {
	return logCtx == nil || logCtx.ShadowContext.State != shadowcontext.StateValid
}

// clearLiteLLMFinancialHeaders removes both the public financial headers AIR
// currently emits and the internal cost-breakdown names it owns. Clearing the
// full set prevents a stale value or an upstream value from escaping on a
// trusted LiteLLM -> AIR request.
func clearLiteLLMFinancialHeaders(headers http.Header) {
	if headers == nil {
		return
	}
	for _, name := range []string{
		liteLLMKeySpendHeader,
		liteLLMKeyMaxBudgetHeader,
		liteLLMKeyRPMLimitHeader,
		liteLLMKeyTPMLimitHeader,
		liteLLMResponseCostHeader,
		liteLLMResponseCostOriginalHeader,
		liteLLMResponseCostDiscountHeader,
		liteLLMResponseCostMarginAmountHeader,
		liteLLMResponseCostMarginPercentHeader,
	} {
		headers.Del(name)
	}
}

func setLiteLLMKeyLimitHeadersForRequest(headers http.Header, tokenInfo *dbmodels.TokenInfo, logCtx *RequestLogContext) {
	if !shouldExposeLiteLLMFinancialHeaders(logCtx) {
		clearLiteLLMFinancialHeaders(headers)
		return
	}
	setLiteLLMKeyLimitHeaders(headers, tokenInfo)
}

func setLiteLLMKeySpendHeaderForRequest(headers http.Header, spend float64, known bool, logCtx *RequestLogContext) {
	if !shouldExposeLiteLLMFinancialHeaders(logCtx) {
		clearLiteLLMFinancialHeaders(headers)
		return
	}
	setLiteLLMKeySpendHeader(headers, spend, known)
}

func setLiteLLMResponseCostHeaderForRequest(headers http.Header, cost float64, logCtx *RequestLogContext) {
	if !shouldExposeLiteLLMFinancialHeaders(logCtx) {
		clearLiteLLMFinancialHeaders(headers)
		return
	}
	setLiteLLMResponseCostHeader(headers, cost)
}

// setLiteLLMKeyLimitHeaders exposes the authenticated key limits using the
// same scalar formatting as LiteLLM's Python response headers. Key spend is
// deliberately separate: it is only emitted from acknowledged database state.
func setLiteLLMKeyLimitHeaders(headers http.Header, tokenInfo *dbmodels.TokenInfo) {
	if headers == nil || tokenInfo == nil {
		return
	}

	if tokenInfo.MaxBudget != nil {
		headers.Set(liteLLMKeyMaxBudgetHeader, formatLiteLLMFloat(*tokenInfo.MaxBudget))
	}
	if tokenInfo.RPMLimit != nil {
		headers.Set(liteLLMKeyRPMLimitHeader, strconv.FormatInt(*tokenInfo.RPMLimit, 10))
	}
	if tokenInfo.TPMLimit != nil {
		headers.Set(liteLLMKeyTPMLimitHeader, strconv.FormatInt(*tokenInfo.TPMLimit, 10))
	}
}

// setLiteLLMKeySpendHeader publishes a committed database value. Unknown or
// unacknowledged state removes any earlier snapshot so stale/cache-derived
// values cannot survive on the response.
func setLiteLLMKeySpendHeader(headers http.Header, spend float64, known bool) {
	if headers == nil {
		return
	}
	if !known {
		headers.Del(liteLLMKeySpendHeader)
		return
	}
	headers.Set(liteLLMKeySpendHeader, formatLiteLLMFloat(spend))
}

func formatLiteLLMFloat(value float64) string {
	formatted := strconv.FormatFloat(value, 'g', -1, 64)
	if !strings.ContainsAny(formatted, ".eE") {
		formatted += ".0"
	}
	return formatted
}

// setLiteLLMResponseCostHeader mirrors the public top-level financial header
// emitted by LiteLLM. Internal original/discount/margin breakdown headers are
// deliberately not exposed by this gateway surface. Streaming callers use
// cost=0 because terminal usage is not yet available when headers are committed.
func setLiteLLMResponseCostHeader(headers http.Header, cost float64) {
	if headers == nil {
		return
	}
	headers.Set(liteLLMResponseCostHeader, strconv.FormatFloat(cost, 'g', -1, 64))
}

// setSuccessfulSSEHeaders disables intermediary response buffering only after
// an upstream has accepted the streaming request. JSON and pre-stream error
// responses must retain their normal buffering semantics.
func setSuccessfulSSEHeaders(headers http.Header, statusCode int) {
	if headers == nil || statusCode < http.StatusOK || statusCode >= http.StatusMultipleChoices {
		return
	}
	headers.Set(accelBufferingHeader, "no")
}

// GetHopByHopHeaders returns a copy of the hop-by-hop headers map for reference.
// Use isHopByHopHeader() to check if a specific header should be filtered.
func GetHopByHopHeaders() map[string]bool {
	// Return a copy to prevent external modifications
	headers := make(map[string]bool)
	for k, v := range hopByHopHeaders {
		headers[k] = v
	}
	return headers
}

// copyRequestHeaders copies headers from source request to destination request,
// skipping hop-by-hop headers and optionally handling the Authorization header.
// Accept-Encoding is also skipped (see copyHeadersSkipAuth for rationale).
func copyRequestHeaders(dst *http.Request, src *http.Request, apiKey string) {
	for key, values := range src.Header {
		canonicalKey := http.CanonicalHeaderKey(key)
		if isHopByHopHeader(canonicalKey) || isPrivacyHeader(canonicalKey) {
			continue
		}
		// Client credentials terminate at AIR. Provider credentials are installed
		// below and client auth headers are never forwarded, even when the proxy
		// credential intentionally has no API key.
		if canonicalKey == "Authorization" || canonicalKey == "X-Api-Key" {
			continue
		}
		// Don't forward Accept-Encoding to upstream (proxy handles per-segment).
		if canonicalKey == "Accept-Encoding" {
			continue
		}
		// Strip internal proxy marker — must not be forwarded to the actual provider.
		if canonicalKey == "X-Aar-Proxy-Client" {
			continue
		}
		for _, value := range values {
			dst.Header.Add(canonicalKey, value)
		}
	}
	if apiKey != "" {
		dst.Header.Set("Authorization", "Bearer "+apiKey)
	}
}

// copyHeadersSkipAuth copies headers from source request to destination request,
// skipping hop-by-hop headers and Authorization header (Authorization will be set separately).
// Accept-Encoding is also skipped: the proxy handles encoding negotiation independently
// for each connection segment (client↔proxy and proxy↔upstream). Forwarding Accept-Encoding
// to upstream prevents Go's Transport from auto-decompressing responses, causing raw gzip
// bytes to flow through instead of decoded content.
func copyHeadersSkipAuth(dst *http.Request, src *http.Request) {
	for key, values := range src.Header {
		canonicalKey := http.CanonicalHeaderKey(key)
		if isHopByHopHeader(canonicalKey) || isPrivacyHeader(canonicalKey) ||
			canonicalKey == "Authorization" || canonicalKey == "X-Api-Key" {
			continue
		}
		// Don't forward Accept-Encoding: proxy manages compression per connection segment.
		// If forwarded, Go's Transport won't auto-decompress upstream gzip responses,
		// leading to raw gzip bytes being passed to converters (gzip parse errors).
		if canonicalKey == "Accept-Encoding" {
			continue
		}
		// Strip internal proxy marker — must not be forwarded to the actual provider.
		if canonicalKey == "X-Aar-Proxy-Client" {
			continue
		}
		for _, value := range values {
			dst.Header.Add(canonicalKey, value)
		}
	}
}

// copyResponseHeaders copies response headers to the response writer,
// skipping hop-by-hop headers and transformation-related headers.
// Note: Content-Encoding is always skipped because Go's http.Client automatically
// decompresses gzip/deflate responses, so the body is already decompressed.
// The caller should compress the body if needed and set Content-Encoding appropriately.
func copyResponseHeaders(w http.ResponseWriter, src http.Header, credType config.ProviderType) {
	for key, values := range src {
		if isHopByHopHeader(key) || isProxyOwnedResponseHeader(key) {
			continue
		}
		// Skip Content-Length and Content-Encoding for all response types
		// - Content-Length will be set based on actual body size
		// - Content-Encoding: Go's http.Client already decompressed the body,
		//   so we skip upstream's Content-Encoding header and let caller set it if recompressing
		// Skip X-Credential-Name — internal header for proxy-to-proxy routing, not exposed to end clients
		if key == "Content-Length" || key == "Content-Encoding" || key == "X-Credential-Name" {
			continue
		}
		for _, value := range values {
			w.Header().Add(key, value)
		}
	}

	// Anthropic exposes its correlation ID as request-id, while OpenAI SDKs
	// consume x-request-id. AIR's public API is OpenAI-compatible, so retain the
	// provider header and add the OpenAI alias without replacing an explicit
	// upstream x-request-id.
	if credType == config.ProviderTypeAnthropic && w.Header().Get("X-Request-Id") == "" {
		if requestID := src.Get("Request-Id"); requestID != "" {
			w.Header().Set("X-Request-Id", requestID)
		}
	}
}
